### ISSUE TITLE
Error: Invalid IV length

### ISSUE THREAD

**Issue by nuriofernandez** [Zazama/cnl2-decrypt#1]
I get an error trying to use your decrypter.
Maybe a problem with the NodeJS version?

```js
internal/crypto/cipher.js:103
    this[kHandle].initiv(cipher, credential, iv, authTagLength);
                  ^

Error: Invalid IV length
    at Decipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
    at Decipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
    at new Decipheriv (internal/crypto/cipher.js:262:22)
    at Object.createDecipheriv (crypto.js:127:10)
    at aes_decrypt (...\node_modules\cnl2-decrypt\index.js:24:27)
    at CNL2Decrypt.decrypt (...\node_modules\cnl2-decrypt\index.js:9:19)
    at Object.<anonymous> (...\src\index.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
```

index.js:15:17
```js
let urls = cnl2.decrypt(rawKey, crypted);
```

**Comment by Zazama** [comment]
Are you passing a key in the format of

`"function+f(){+return+'6653705553628279363377636c76645a';}"`

or just

`6653705553628279363377636c76645a`?

**Comment by nuriofernandez** [comment]
I'm passing the whole `"function+f(){+return+'6653705553628279363377636c76645a';}"`

**Comment by nuriofernandez** [comment]
I've read at StackOverflow that the `crypto` library has changed, not sure if that's related to this problem.
https://stackoverflow.com/a/42485606/7343009

**Comment by Zazama** [comment]
Oh, sorry, there's a mistake in the README, it must be `cnl2.decrypt(crypted, rawKey);` instead of `cnl2.decrypt(rawKey, crypted);`

**Comment by nuriofernandez** [comment]
Perfect, it's now working!
